# ORDER
SPACESHIP_PROMPT_ORDER=(
  dir
  venv
  git
  exit_code
  char
)

# DIR
SPACESHIP_DIR_TRUNC='1'
SPACESHIP_DIR_COLOR=blue

# GIT
SPACESHIP_GIT_BRANCH_COLOR=green
SPACESHIP_GIT_STATUS_COLOR=yellow

# VENV
SPACESHIP_VENV_COLOR=yellow

# PROMPT
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=false
SPACESHIP_PROMPT_PREFIXES_SHOW=false
