# Change prefix from ctrl+b to ctrl+space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'

# Theme
set -g @themepack 'basic'

# Global config
set -g history-limit 30000

# Use mouse to select pane
set -g mouse on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'

# Source tmux config
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Close pane without confirmation
bind-key x kill-pane

# Make scrolling with wheels work
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M

# Switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D


# These bindings (^B + and ^B -) are a “zoom” feature. 
# Focused on a given pane, ^B + will promote the pane to be its own window. 
# Then you can do OS-native mark and copy all you want, no panes to worry about. 
# When you’re done, just use ^B - to turn the window back into a pane, right where it was before.
unbind +
bind + \
  new-window -d -n tmux-zoom 'clear && echo TMUX ZOOM && read' \;\
  swap-pane -s tmux-zoom.0 \;\
  select-window -t tmux-zoom
    
unbind -
bind - \
  last-window \;\
  swap-pane -s tmux-zoom.0 \;\
  kill-window -t tmux-zoom
