# espanso configuration file

matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"
  - trigger: "oe"
    replace: "œ"
    propagate_case: true
  - trigger: "..."
    replace: "…"
  - trigger: ":..."
    replace: "…"
  - trigger: ":i18n"
    replace: "internationalization"
  - trigger: ":l10n"
    replace: "localization"
  - trigger: ":g11n"
    replace: "globalization"
  - trigger: ":a11y"
    replace: "accessibility"
  - trigger: ":abbr"
    replace: "abbreviation"

toggle_key: OFF
passive_key: CTRL
