"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$php\
$python\
$rust\
$line_break\
$character\
"""

continuation_prompt = "[▶](bold green) "

[character]
success_symbol = "[➜](bold green)"

[python]
symbol = " "

[git_branch]
symbol = " "
