invert_scrolling = true

[theme]
theme = "dracula.toml"

[icons]
icons = "awesome6"

[[block]]
block = "music"
player = "spotify"
format = "  $icon {$combo.str(max_w:25,rot_interval:0.5)  $prev  $play  $next}  "
separator = " - "
[[block.click]]
button = "left"
action = "play_pause"
[block.theme_overrides]
info_bg = "#50fa7b"
idle_bg = "#282A36"
idle_fg = "#F8F8F2"
[block.icons_overrides]
music = "<span font='Font Awesome 6 Brands 11'>\uf1bc</span>"

# Bose QC35 II
[[block]]
block = "bluetooth"
mac = "2C:41:A1:04:21:AA"
format = "  \uf025  "
disconnected_format = "  \uf025 x  "
[block.theme_overrides]
good_bg = "#bd93f9"

# BIMBADABIMBIMBADABADABOOM
[[block]]
block = "bluetooth"
mac = "C0:28:8D:91:9E:7C"
format = "  \uf192  "
disconnected_format = ""
[block.theme_overrides]
good_bg = "#bd93f9"

# Apple Airpods
[[block]]
block = "bluetooth"
mac = "AC:90:85:DC:48:8C"
format = "  \uf179 \uf58f  "
disconnected_format = "  \uf179 \uf58f x  "
[block.theme_overrides]
good_bg = "#bd93f9"

# Logitech MX Master
[[block]]
block = "bluetooth"
mac = "F8:E5:3A:4D:12:61"
format = "  $icon { $percentage|}  "
disconnected_format = "  $icon x  "
[block.theme_overrides]
good_bg = "#282A36"
good_fg = "#F8F8F2"
info_bg = "#282A36"
info_fg = "#F8F8F2"

[[block]]
block = "memory"
format = "  $icon $mem_used  "

[[block]]
block = "cpu"
interval = 5
format = "  $icon $utilization $frequency  "

[[block]]
block = "temperature"
interval = 10
format = "  $icon $average  "

[[block]]
block = "sound"
format = "  $icon {$volume.eng(w:2) |}  "

[[block]]
block = "toggle"
format = "  $icon  "
command_state = "cat /tmp/wired-dnd-state | grep on"
command_on = "wired --dnd on && echo 'on' > /tmp/wired-dnd-state"
command_off = "wired --dnd off && echo 'off' > /tmp/wired-dnd-state"
interval = 10
icon_on = "bell-slash"
icon_off = "bell"

[[block]]
block = "time"
format = "  $icon $timestamp.datetime(f:'%d/%m/%Y %R', l:fr_FR)  "
timezone = "Europe/Paris"
interval = 5

[[block]]
block = "battery"
interval = 10
format = "  $icon $percentage $time  "
not_charging_format = "  $icon $percentage  "
full_threshold = 100
good = 60
info = 50
warning = 20
critical = 10
[block.theme_overrides]
good_bg = "#282a36"
good_fg = "#f8f8f2"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
format = " \uf042 $temperature "
click_temp = 4500

