[theme]
theme = "dracula.toml"
#scrolling = "natural"

[icons]
name = "awesome6"

[icons.overrides]
music_next = "\uf051"
music_prev = "\uf048"

[[block]]
block = "music"
player = "spotify"
#on_click = "dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"
format = " $icon {$combo.str(max_w:25,rot_interval:0.5) $prev $play $next|}"
[block.theme_overrides]
info_bg = "#50fa7b"
idle_bg = "#282A36"
idle_fg = "#F8F8F2"
[block.icons_overrides]
music = "<span font='Font Awesome 6 Brands 11'>\uf1bc</span>"

#[[block]]
#block = "music"
#interface_name_exclude = ["spotify"]
#buttons = ["prev", "play", "next"]
#hide_when_empty = true
#marquee_interval = 5
#marquee_speed = 0.3
#max_width = 120
#dynamic_width = true
#format = "{combo}"
#[block.icons_overrides]
#music = "\uf144"

# Bose QC35 II
[[block]]
block = "bluetooth"
mac = "2C:41:A1:04:21:AA"
format = "\uf025"
#format_unavailable = "\uf025 x"
#hide_disconnected = false
[block.theme_overrides]
good_bg = "#bd93f9"

# BIMBADABIMBIMBADABADABOOM
[[block]]
block = "bluetooth"
mac = "C0:28:8D:91:9E:7C"
format = "\uf192"
#format_unavailable = "\uf192 x"
#hide_disconnected = true
[block.theme_overrides]
good_bg = "#bd93f9"

# Apple Airpods
[[block]]
block = "bluetooth"
mac = "AC:90:85:DC:48:8C"
format = "\uf179 \uf58f"
#format_unavailable = "\uf179 \uf58f x"
#hide_disconnected = true
[block.theme_overrides]
good_bg = "#bd93f9"

# Logitech MX Master
[[block]]
block = "bluetooth"
mac = "F8:E5:3A:4D:12:61"
format = "{percentage}"
#format_unavailable = "🖱 x"
#hide_disconnected = false
[block.theme_overrides]
good_bg = "#282A36"
good_fg = "#F8F8F2"
info_bg = "#282A36"
info_fg = "#F8F8F2"

[[block]]
block = "memory"
#display_type = "memory"
#format_mem = "{mem_used}"

[[block]]
block = "cpu"
interval = 5
format = "$utilization $frequency"

[[block]]
block = "temperature"
#collapsed = false
interval = 10
format = "$averageC°"

#[[block]]
#block = "net"
#device = "wlp0s20f3"
#format = "{speed_down;K*b} {speed_up;K*b}"
#interval = 2

[[block]]
block = "sound"

#[[block]]
#block = "backlight"
#device = "intel_backlight"
#invert_icons = true

[[block]]
block = "toggle"
format = " $icon DnD"
command_state = "cat /tmp/wired-dnd-state | grep on"
command_on = "wired --dnd on && echo 'on' > /tmp/wired-dnd-state"
command_off = "wired --dnd off && echo 'off' > /tmp/wired-dnd-state"
interval = 10
icon_on = "bell-slash"
icon_off = "bell"

[[block]]
block = "time"
format = "%d/%m/%Y %R"
timezone = "Europe/Paris"
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
full_threshold = 100
good = 60
info = 50
warning = 20
critical = 10
[block.theme_overrides]
good_bg = "#282a36"
good_fg = "#f8f8f2"
